# Generated by Django 2.2.1 on 2019-06-11 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0003_auto_20190611_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogrupomodel',
            name='data_entrada',
            field=models.DateField(null=True, verbose_name='Data de entrada'),
        ),
        migrations.AddField(
            model_name='usuariogrupomodel',
            name='data_saida',
            field=models.DateField(null=True, verbose_name='Data de Saida'),
        ),
        migrations.AlterField(
            model_name='usuariogrupomodel',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Cadastro'),
        ),
    ]
