# Generated by Django 2.2.1 on 2019-06-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0004_auto_20190611_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoModel',
            fields=[
                ('permissao_id', models.AutoField(primary_key=True, serialize=False)),
                ('permissao_nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('permissao_read', models.BooleanField(verbose_name='Permissao de leitura')),
                ('permissao_write', models.BooleanField(verbose_name='Permissao de escrita')),
                ('permissao_delete', models.BooleanField(verbose_name='Permissao de exclusão')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['permissao_nome'],
            },
        ),
        migrations.AddField(
            model_name='grupomodel',
            name='grupo_permissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.PermissaoModel'),
        ),
    ]
