# Generated by Django 2.2.1 on 2019-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0005_auto_20190615_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContasModel',
            fields=[
                ('plano_contas_id', models.AutoField(primary_key=True, serialize=False)),
                ('plano_contas_referencial', models.CharField(max_length=45, verbose_name='Referencial')),
                ('plano_contas_descricao', models.CharField(max_length=45, verbose_name='Descricao')),
                ('plano_contas_inicio_validade', models.DateField(null=True, verbose_name='Inicio Validade')),
                ('plano_contas_fim_validade', models.DateField(null=True, verbose_name='Fim Validade')),
                ('plano_contas_tipo', models.CharField(max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'PlanoConta',
                'verbose_name_plural': 'PlanosContas',
                'ordering': ['plano_contas_descricao'],
            },
        ),
    ]
